"use client";

import { Check, ChevronDown, LoaderCircle, Minus, Plus, Search, ShoppingBag, Sparkles, X } from "lucide-react";
import { useMemo, useState } from "react";
import type { Product } from "@/lib/catalog";

type CartItem = Product & { quantity: number };
type Checkout = { customerName: string; customerEmail: string; phone: string; address: string };
const categories = ["All", "Walnuts", "Nuts", "Dried fruit", "Seeds"];
const weightsFor = (product: Product) => product.unit === "100g" ? ["100g", "250g", "500g"] : ["250g", "500g", "1kg"];
const priceFor = (product: Product, weight: string) => Math.round(product.price * (parseInt(weight, 10) / parseInt(product.unit, 10)));

export default function Storefront({ products }: { products: Product[] }) {
  const [cart, setCart] = useState<CartItem[]>([]);
  const [open, setOpen] = useState(false);
  const [checkoutOpen, setCheckoutOpen] = useState(false);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All");
  const [sort, setSort] = useState("featured");
  const [weights, setWeights] = useState<Record<string, string>>({});
  const [notice, setNotice] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [checkout, setCheckout] = useState<Checkout>({ customerName: "", customerEmail: "", phone: "", address: "" });
  const add = (product: Product) => {
    const unit = weights[product.id] || product.unit;
    const selected = { ...product, unit, price: priceFor(product, unit) };
    setCart((current) => current.some((item) => item.id === product.id && item.unit === unit) ? current.map((item) => item.id === product.id && item.unit === unit ? { ...item, quantity: item.quantity + 1 } : item) : [...current, { ...selected, quantity: 1 }]);
    setNotice(`${product.name} added to your bag`);
    window.setTimeout(() => setNotice(null), 2200);
  };
  const change = (id: string, amount: number) => setCart((current) => current.flatMap((item) => item.id === id ? (item.quantity + amount > 0 ? [{ ...item, quantity: item.quantity + amount }] : []) : [item]));
  const count = cart.reduce((sum, item) => sum + item.quantity, 0);
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0);
  const filtered = useMemo(() => products.filter((product) => `${product.name} ${product.hindiName} ${product.category}`.toLowerCase().includes(query.toLowerCase()) && (category === "All" || product.category === category)).sort((a, b) => sort === "price-low" ? a.price - b.price : sort === "price-high" ? b.price - a.price : Number(b.featured) - Number(a.featured)), [category, products, query, sort]);
  const submitOrder = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setBusy(true);
    const response = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...checkout, items: cart.map(({ id, name, unit, quantity, price }) => ({ id, name, unit, quantity, price })), total }) });
    const result = await response.json();
    if (!response.ok) { setNotice(result.error || "Please check your order details."); setBusy(false); return; }
    setCart([]);
    window.location.href = result.whatsappUrl;
  };
  return <div className="relative">
    <div className="mt-10 flex flex-col gap-4 border-y border-[var(--forest)]/10 py-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-2 overflow-x-auto pb-1">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full px-4 py-2 text-sm font-bold transition ${category === item ? "bg-[var(--forest)] text-white" : "bg-[var(--background)] text-[var(--muted)] hover:text-[var(--forest)]"}`}>{item}</button>)}</div><div className="flex gap-3"><label className="flex min-w-0 flex-1 items-center gap-2 rounded-full border border-[var(--forest)]/15 bg-[var(--background)] px-4 py-2 text-sm text-[var(--muted)] lg:w-64"><Search size={16} /><input aria-label="Search products" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search the collection" className="min-w-0 flex-1 bg-transparent outline-none placeholder:text-[var(--muted)]" /></label><label className="flex items-center gap-2 rounded-full border border-[var(--forest)]/15 bg-[var(--background)] px-4 py-2 text-sm font-semibold text-[var(--forest)]"><span className="sr-only">Sort products</span><select aria-label="Sort products" value={sort} onChange={(event) => setSort(event.target.value)} className="appearance-none bg-transparent outline-none"><option value="featured">Featured</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select><ChevronDown size={15} /></label></div></div>
    <div className="mt-6 flex items-center justify-between"><p className="text-sm text-[var(--muted)]">Showing <strong className="text-[var(--forest)]">{filtered.length}</strong> of {products.length} favourites</p><p className="hidden items-center gap-2 text-xs font-bold uppercase tracking-wider text-[var(--clay)] sm:flex"><Sparkles size={14} /> Packed fresh for you</p></div>
    {filtered.length ? <div className="mt-8 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((product) => { const selectedWeight = weights[product.id] || product.unit; return <article key={product.id} className="product-card group"><div className="relative aspect-[.9] overflow-hidden rounded-[1.25rem] bg-[#e6e6d8]"><img src={product.imageUrl} alt={product.name} className="product-image h-full w-full object-cover mix-blend-multiply" /><span className="absolute left-4 top-4 rounded-full bg-[var(--paper)] px-3 py-1 text-[11px] font-bold uppercase tracking-wider text-[var(--clay)]">{product.badge}</span><button aria-label={`Add ${product.name} to cart`} onClick={() => add(product)} className="absolute bottom-4 right-4 flex h-11 w-11 items-center justify-center rounded-full bg-[var(--forest)] text-white shadow-lg transition hover:scale-105 hover:bg-[var(--clay)]"><Plus size={20} /></button></div><div className="pt-4"><div className="flex items-start justify-between gap-4"><div><h3 className="display text-2xl text-[var(--forest)]">{product.name}</h3><p className="mt-1 text-sm text-[var(--muted)]">{product.hindiName}</p></div><p className="shrink-0 text-sm font-bold text-[var(--forest)]">₹{priceFor(product, selectedWeight)}</p></div><div className="mt-4 flex gap-1 rounded-xl bg-[var(--background)] p-1">{weightsFor(product).map((weight) => <button key={weight} onClick={() => setWeights((current) => ({ ...current, [product.id]: weight }))} className={`flex-1 rounded-lg py-2 text-xs font-bold transition ${selectedWeight === weight ? "bg-[var(--paper)] text-[var(--forest)] shadow-sm" : "text-[var(--muted)]"}`}>{weight}</button>)}</div><div className="mt-3 flex items-center justify-between gap-3"><p className="max-w-xs text-xs leading-5 text-[var(--muted)]">{product.description}</p><button onClick={() => add(product)} className="shrink-0 text-xs font-bold uppercase tracking-wider text-[var(--clay)]">Quick add</button></div></div></article>; })}</div> : <div className="mt-12 rounded-2xl bg-[var(--background)] px-6 py-16 text-center"><p className="display text-3xl text-[var(--forest)]">Nothing here yet.</p><p className="mt-2 text-sm text-[var(--muted)]">Try another search or category.</p></div>}
    <button onClick={() => setOpen(true)} className="fixed bottom-6 right-6 z-30 flex items-center gap-3 rounded-full bg-[var(--clay)] px-5 py-3 text-sm font-bold text-white shadow-2xl transition hover:bg-[var(--forest)]"><ShoppingBag size={18} /> Bag {count > 0 && <span className="flex h-6 min-w-6 items-center justify-center rounded-full bg-white px-1 text-xs text-[var(--clay)]">{count}</span>}</button>
    {notice && <div role="status" className="fixed bottom-20 left-1/2 z-30 -translate-x-1/2 rounded-full bg-[var(--forest)] px-5 py-3 text-sm font-bold text-white shadow-xl">{notice}</div>}
    {open && <div className="fixed inset-0 z-40 flex justify-end bg-[var(--forest)]/30 backdrop-blur-sm"><aside className="flex h-full w-full max-w-md flex-col bg-[var(--paper)] p-7 shadow-2xl"><div className="flex items-center justify-between border-b border-[var(--forest)]/10 pb-5"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--clay)]">Your selection</p><h2 className="display mt-1 text-3xl text-[var(--forest)]">The good stuff</h2></div><button aria-label="Close cart" onClick={() => setOpen(false)} className="rounded-full p-2 text-[var(--forest)] hover:bg-[var(--leaf)]"><X size={20} /></button></div><div className="flex-1 overflow-y-auto py-5">{cart.length === 0 ? <div className="flex h-full flex-col items-center justify-center text-center"><ShoppingBag className="text-[var(--gold)]" size={38} /><p className="mt-4 font-bold text-[var(--forest)]">Your bag is waiting.</p><p className="mt-2 text-sm text-[var(--muted)]">Add a little goodness to get started.</p></div> : cart.map((item) => <div key={`${item.id}-${item.unit}`} className="flex gap-4 border-b border-[var(--forest)]/10 py-4"><img src={item.imageUrl} alt="" className="h-20 w-20 rounded-xl object-cover mix-blend-multiply" /><div className="min-w-0 flex-1"><p className="font-bold text-[var(--forest)]">{item.name}</p><p className="mt-1 text-sm text-[var(--muted)]">₹{item.price} / {item.unit}</p><div className="mt-3 flex items-center gap-3"><button aria-label={`Decrease ${item.name}`} onClick={() => change(item.id, -1)} className="rounded-full border p-1"><Minus size={14} /></button><span className="text-sm font-bold">{item.quantity}</span><button aria-label={`Increase ${item.name}`} onClick={() => change(item.id, 1)} className="rounded-full border p-1"><Plus size={14} /></button></div></div></div>)}</div><div className="border-t border-[var(--forest)]/10 pt-5"><div className="flex justify-between text-lg font-bold text-[var(--forest)]"><span>Total</span><span>₹{total}</span></div><button disabled={!cart.length} onClick={() => { setOpen(false); setCheckoutOpen(true); }} className="mt-5 flex w-full items-center justify-center gap-2 rounded-full bg-[var(--forest)] px-5 py-3 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40"><Check size={17} /> Continue to order</button><p className="mt-3 text-center text-xs text-[var(--muted)]">Order ID generated before WhatsApp · Cash on delivery</p></div></aside></div>}
    {checkoutOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[var(--forest)]/40 px-4 py-6 backdrop-blur-sm"><form onSubmit={submitOrder} className="w-full max-w-lg rounded-[1.5rem] bg-[var(--paper)] p-7 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[var(--clay)]">Order details</p><h2 className="display mt-2 text-3xl text-[var(--forest)]">Almost at your door.</h2></div><button type="button" aria-label="Close order details" onClick={() => setCheckoutOpen(false)} className="rounded-full p-2"><X size={20} /></button></div><p className="mt-3 text-sm text-[var(--muted)]">We create your order record first, then open WhatsApp with the order ID and full summary.</p><div className="mt-6 grid gap-3"><input required placeholder="Full name" value={checkout.customerName} onChange={(event) => setCheckout({ ...checkout, customerName: event.target.value })} className="rounded-xl border border-[var(--forest)]/15 bg-white px-4 py-3 text-sm outline-none focus:border-[var(--clay)]" /><input required type="tel" placeholder="Phone number" value={checkout.phone} onChange={(event) => setCheckout({ ...checkout, phone: event.target.value })} className="rounded-xl border border-[var(--forest)]/15 bg-white px-4 py-3 text-sm outline-none focus:border-[var(--clay)]" /><input type="email" placeholder="Email for order updates (optional)" value={checkout.customerEmail} onChange={(event) => setCheckout({ ...checkout, customerEmail: event.target.value })} className="rounded-xl border border-[var(--forest)]/15 bg-white px-4 py-3 text-sm outline-none focus:border-[var(--clay)]" /><textarea required placeholder="Delivery address" value={checkout.address} onChange={(event) => setCheckout({ ...checkout, address: event.target.value })} className="min-h-24 rounded-xl border border-[var(--forest)]/15 bg-white px-4 py-3 text-sm outline-none focus:border-[var(--clay)]" /></div><div className="mt-5 flex items-center justify-between border-t border-[var(--forest)]/10 pt-5"><span className="font-bold text-[var(--forest)]">Order total</span><span className="text-lg font-bold text-[var(--forest)]">₹{total}</span></div><button disabled={busy} className="mt-5 flex w-full items-center justify-center gap-2 rounded-full bg-[var(--clay)] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{busy && <LoaderCircle className="animate-spin" size={17} />} {busy ? "Creating order..." : "Create order & open WhatsApp"}</button></form></div>}
  </div>;
}
