import { ArrowLeft, KeyRound, Mail } from "lucide-react";
import Link from "next/link";
import { requestOtp, verifyOtp } from "@/app/actions/auth";

export default async function AdminLoginPage({ searchParams }: { searchParams: Promise<{ error?: string; sent?: string; email?: string }> }) {
  const params = await searchParams;
  const email = params.email || process.env.ADMIN_EMAIL || "admin@mevahouse.local";
  const sent = params.sent === "1";
  const message = params.error === "email-config" ? "Email delivery is not configured. Add RESEND_API_KEY and EMAIL_FROM." : params.error === "code" ? "That code is incorrect or expired." : params.error === "unauthorized" ? "Use the configured administrator email." : null;
  return <main className="flex min-h-screen items-center justify-center bg-[var(--forest)] px-6 py-12"><div className="w-full max-w-md rounded-[2rem] bg-[var(--paper)] p-8 shadow-2xl sm:p-12"><Link href="/" className="flex items-center gap-2 text-sm font-bold text-[var(--muted)]"><ArrowLeft size={16} /> Back to storefront</Link><div className="mt-12"><KeyRound className="text-[var(--clay)]" size={28} /><h1 className="display mt-5 text-4xl text-[var(--forest)]">Admin access.</h1><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Use a one-time email code to manage the Meva House collection.</p></div>{message && <p className="mt-6 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{message}</p>}{!sent ? <form action={requestOtp} className="mt-8 space-y-5"><input type="hidden" name="flow" value="admin" /><label className="block text-sm font-bold text-[var(--forest)]">Admin email<input name="email" type="email" required defaultValue={email} className="mt-2 w-full rounded-xl border border-[var(--forest)]/15 bg-white px-4 py-3 font-normal outline-none focus:border-[var(--clay)]" /></label><button className="flex w-full items-center justify-center gap-2 rounded-full bg-[var(--forest)] px-5 py-3 text-sm font-bold text-white transition hover:bg-[var(--clay)]"><Mail size={17} /> Send admin code</button></form> : <div className="mt-8 space-y-5"><form action={verifyOtp} className="space-y-5"><input type="hidden" name="flow" value="admin" /><input type="hidden" name="email" value={email} /><div className="rounded-xl bg-[var(--leaf)]/50 p-4 text-sm text-[var(--forest)]">Code sent to <strong>{email}</strong>.</div><label className="block text-sm font-bold text-[var(--forest)]">One-time code<input name="code" inputMode="numeric" pattern="[0-9]{6}" maxLength={6} autoComplete="one-time-code" required autoFocus className="mt-2 w-full rounded-xl border border-[var(--forest)]/15 bg-white px-4 py-3 text-center text-2xl tracking-[.5em] outline-none focus:border-[var(--clay)]" /></label><button className="w-full rounded-full bg-[var(--forest)] px-5 py-3 text-sm font-bold text-white transition hover:bg-[var(--clay)]">Verify admin access</button></form><div className="flex items-center justify-between text-sm font-bold"><form action={requestOtp}><input type="hidden" name="flow" value="admin" /><input type="hidden" name="resend" value="1" /><input type="hidden" name="email" value={email} /><button className="text-[var(--clay)]">Resend code</button></form><Link href="/admin/login" className="text-[var(--muted)]">Use a different email</Link></div></div>}</div></main>;
}
